name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: |
          git config --global init.defaultBranch master
          git config --global user.email "leo.wei.liu@gmail.com"
          git config --global user.name "smilingleo"          

      - name: Check out blog code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Check out site code
        uses: actions/checkout@v3
        with:
          repository: 'smilingleo/smilingleo.github.io'
          token: ${{ secrets.PAT_TOKEN }}
          path: 'public'
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: |
          npm i
          #find node_modules -iname graphql
          rm -rf node_modules/gatsby/node_modules/graphql
          rm -rf node_modules/graphql-skip-limit/node_modules/graphql
          rm -rf node_modules/relay-compiler/node_modules/graphql
          cd public
          git remote -v
          cd ..
          yarn deploy
          cd public
          git add .
          git commit -m 'new post'
          git push origin master
      - run: echo "ğŸ This job's status is ${{ job.status }}."
