name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out blog code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."

      - name: Check out site code
        uses: actions/checkout@v3
        with:
          repository: 'smilingleo/smilingleo.github.io'
          path: '${{ github.repository }}/my-blog-code/public'
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          ls ${{ github.workspace }}/my-blog-code/public
        
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: |
          npm i
          yarn deploy
      - run: echo "ğŸ This job's status is ${{ job.status }}."
